version: '3'
volumes:
  grafana-storage:
  prometheus:
services:
  prometheus:
    image: prom/prometheus
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    volumes:
      - D:/Projetos Consul/Docker/prometheus-data:/prometheus-data
      - D:/Projetos Consul/Docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  speedtest:
    image: speedtest
    ports:
      - 9112:9112
    depends_on:
      - prometheus    